FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

ENV PATH=$PATH:/app

COPY ["starter.py", "Pipfile", "Pipfile.lock", "./"]

RUN pip install --upgrade & pip install pipenv
RUN pipenv install --system

ENTRYPOINT [ "python", "batch.py" ]
